# Generated by Django 4.0.5 on 2022-06-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_text', models.CharField(max_length=20000)),
                ('problem_input', models.CharField(max_length=20000)),
                ('problem_output', models.CharField(max_length=20000)),
                ('problem_number', models.IntegerField(default=0)),
            ],
        ),
    ]
